#COLORS##
COLOR_NT_AUC = '#3C00FF'
COLOR_NT_PREC = '#747DC6'
COLOR_NT_NPV = '#281B7C'

COLOR_INTARNA_AUC = 'orange'
COLOR_INTARNA_PREC = '#FFB450'
COLOR_INTARNA_NPV = '#A57617'

COLOR_ENS_AUC = 'green'
COLOR_ENS_PREC = '#70DC6C'
COLOR_ENS_NPV = '#18791B'


COLOR_PRIBLUS = 'gray'
COLOR_RNAUP = 'red'
COLOR_RNAPLEX = 'pink'
COLOR_RNAHYBRID = 'purple'
COLOR_RNACOFOLD = 'brown'
COLOR_RISEARCH2 = 'olive'
COLOR_ASSA = 'cyan'