#!/bin/bash

folders=('arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0087' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0093' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0094' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0095' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0096' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0097' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0098' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0099' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0100' 'arch2_PARISfinetuned_PARIStest0023_PARISfinetunedFPweight_PARIStest0086_PARISfinetunedSPLASHFPweight_PARIStest0101')

for folder in "${folders[@]}"; do

    nohup python run_binary_cl_on_test_500.py --folder="$folder" --how=val &> run_binary_cl_on_test_val.out &
    pid1=$!

    wait "$pid1"
done

# nohup ./run_multiple_folders_on_test500DROP.sh &> run_multiple_folders_on_test500DROP.out &



#  # Wait for each command within the folder iteration to complete
# wait "$pid1"
